### ISSUE TITLE
ValueError: Dimensions must be equal, but are 1600 and 1100 for 'model/RNN/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [1,1600], [1100,3200].

### ISSUE THREAD

**Issue by Ashchenlovelive** [YangzlTHU/RNN-Stega#1]
When I try to run huffman_movie_v2.py, I got the error:

Traceback (most recent call last):
  File "huffman_movie_v2.py", line 170, in <module>
    tf.app.run()
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "huffman_movie_v2.py", line 85, in main
    mtest = Model.Model(is_training=False, config=config)
  File "/data-x/g10/deepspeech_model_watermarking/RNN-Stega/Model.py", line 48, in __init__
    (cell_output, state) = cell(inputs[:, time_step, :], state)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 248, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
ValueError: in converted code:
    relative to /public/anaconda2/envs/deepspeech_wm/lib/python3.6/site-packages/tensorflow/python:

    ops/rnn_cell_impl.py:1719 call
        cur_inp, new_state = cell(cur_inp, cur_state)
    ops/rnn_cell_impl.py:767 call
        array_ops.concat([inputs, h], 1), self._kernel)
    util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    ops/math_ops.py:2647 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    ops/gen_math_ops.py:5925 mat_mul
        name=name)
    framework/op_def_library.py:788 _apply_op_helper
        op_def=op_def)
    util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    framework/ops.py:3616 create_op
        op_def=op_def)
    framework/ops.py:2027 __init__
        control_input_ops)
    framework/ops.py:1867 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 1600 and 1100 for 'model/RNN/RNN/multi_rnn_cell/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [1,1600], [1100,3200].

**Comment by nsgyyg** [comment]
I would like to ask, did you solve the problem?
